# Generated by Django 4.1.7 on 2023-02-25 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'ordering': ['name', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subscription_price', models.IntegerField(default=0)),
                ('isNew', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojocs.platform')),
            ],
            options={
                'ordering': ['name', 'subscription_price', 'isNew'],
            },
        ),
        migrations.CreateModel(
            name='videogames_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videogame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojocs.videogame')),
            ],
        ),
        migrations.AddField(
            model_name='videogame',
            name='users',
            field=models.ManyToManyField(through='videojocs.videogames_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='platforms_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojocs.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='users',
            field=models.ManyToManyField(through='videojocs.platforms_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
